version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    ports:
      - "5555:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
