version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: pg-data
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    name: nest-db
