version: '3.8'
services:
  testing-db:
    image: postgres:13-alpine
    restart: always
    container_name: testing-db
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-db
      - DB_PORT=5444
    # env_file:
    #   - .env.test
    volumes:
      - testing-db:/var/lib/postgresql/data

volumes:
  testing-db:
    name: nest-db-testing
    driver: local
