version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
        - ./:/app
        - /app/node_modules

  postgres:
    image: postgres:13
    restart: always
    container_name: pg-data
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    name: nest-db
